fluxendd/fluxend

.env.example
cmd/seed.go
cmd/server.go
controllers/setting_controller.go
database/migrations/20250117084028_add_settings_table.sql
database/seeders/seed_settings.go
message/message.go
middlewares/allow_backup_middleware.go
middlewares/allow_form_middleware.go
middlewares/allow_project_middleware.go
middlewares/allow_storage_middleware.go
middlewares/form_toggle_middleware.go
middlewares/request_logger_middleware.go
repositories/setting_repository.go
routes/backup_routes.go
routes/form_routes.go
routes/project_routes.go
routes/storage_routes.go
services/form_service.go
services/setting_service.go
services/user_service.go

App is limited to `.env` settings at the moment. This has drawback. App container must be re-built for new settings to take effect. Also, you must have server access to update values. 
This PR changes that by moving settings to database and exposing them via endpoints. Users will then be able to adjust settings from their dashboard.

Add support for settings

---

.env.example
services/backblze_service.go
services/storage_provider_service.go

Backblaze is an S3 alternative with much cheaper options. Many small businesses might not be able to afford S3. Hence, they should have the option to opt for something more affordable. And we should get out of their way by giving them the tools they need. 
This pull request introduce BackBlaze as 3rd storage option after S3 and [Dropbox](https://github.com/fluxton-io/fluxton/pull/51)
**Changes**
- Introduce `BackblazeService` which implements all storage related logic
- Enable storage driver switch

[Feature] Support BackBlze storage driver

---

internal/api/middlewares/auth_middleware.go
internal/config/constants/user.go

In different cases, users might want to have multiple sessions. They may want to login from two different browsers/devices etc. This pull request allows them to have upto 5 active sessions. We previously allowed only 1.
Fixes: https://github.com/fluxton-io/fluxton/issues/23

[Fix] Allow multiple login sessions

---

Makefile
internal/api/handlers/backup.go
internal/api/handlers/column.go
internal/api/handlers/container.go
internal/api/handlers/file.go
internal/api/handlers/form.go
internal/api/handlers/form_field.go
internal/api/handlers/form_response.go
internal/api/handlers/function.go
internal/api/handlers/log.go
internal/api/handlers/organization.go
internal/api/handlers/organization_member.go
internal/api/handlers/project.go
internal/api/handlers/setting.go
internal/api/handlers/table.go
internal/api/handlers/user.go
internal/api/mapper/backup.go
internal/api/mapper/column.go
internal/api/mapper/container.go
internal/api/mapper/file.go
internal/api/mapper/form.go
internal/api/mapper/function.go
internal/api/mapper/log.go
internal/api/mapper/organization.go
internal/api/mapper/project.go
internal/api/mapper/setting.go
internal/api/mapper/table.go
internal/api/mapper/user.go

The response mappers directory is not optimal. There is dedicated directory for each type and mostly contains a file with two methods. These are found at `internal/api/mapper`
This PR will throw away directories and put all files in same directory. 
**Before**
```go
projectMapper "fluxton/internal/api/mapper/project"
projectMapper.ToResource
```
**After**
```go
"fluxton/internal/api/mapper"
mapper.ToProjectResource
```

[FLX-56] Cleaner response mappers

---

Dockerfile
README.md
docs/docs.go
docs/swagger.json
docs/swagger.yaml
internal/api/dto/logging/mapper.go
internal/api/dto/logging/requests.go
internal/api/handlers/log.go
internal/database/repositories/container.go
internal/database/repositories/request_log.go
internal/domain/logging/repository.go
internal/domain/logging/service.go
internal/domain/logging/types.go

**Context**
We will be supporting logs. Users should be able to view request logs and also filter through them with different parameters.
**What changes**
Allow `GET` => `api/admin/logs` users to search by different parameters. These parameters include
- `userUuid`: all request from a specific user
- `status`: all request with HTTP status e.g `200`
- `method`: all requests with HTTP method e.g `POST`
- `endpoint`: all requests to an endpoint
- `ipAddress:` all request from an IP
- `limit`: number of results per page
- `page`: current page
- `sort`: sort results by
- `order`: order results by
[Source](https://github.com/fluxton-io/fluxton/blob/f6b36ee0ed665c45a0f445f9fc7180221b1aa7ad/internal/api/dto/logging/requests.go#L13)

[FLX-16] Support log search

---

web/.env.sample
web/app/tools/fetch.ts

**Problem**
The problem was same env being used for both container to container and public request.
**Changes**
- Use separate `.env` URLs for server and client

FLX-108: Address CORS issue

---

internal/app/commands/server.go
internal/config/constants/general.go

**Why**
Misconfiguration can cause heartache and pulled out hair. This can be avoided if API server validates configs and common pitfalls and throws appropriate errors
**What changes**
- Ensures required `.env` variables are present
- `JWT_SECRET` is of minimum 32 chars

[FLX-112] Validate required ENV vars

---

internal/api/handlers/health.go
internal/domain/health/entity.go
internal/domain/health/service.go
internal/domain/health/types.go
pkg/size_conversion.go

**Why**
The current endpoint only returns status of system. It doesn't provide details about disk and cpu usage. 
**What changes**
- Introduce `disk_usage` which percentage of disk used
- Introduce `disk_available` which shows available space
- Introduce `disk_total`
- Introduce `cpu_usage` to show CPU usage in percentage
- Introduce `cpu_cores`

[FLX-113] Extend health endpoint

---

docs/docs.go
docs/openapi.json
docs/swagger.json
docs/swagger.yaml
internal/api/handlers/user.go
internal/api/routes/user.go

**Why**
We had a `/users/{userUUID}` endpoint in place already. Though we were missing an endpoint for automatically fetching logged-in user's info https://github.com/fluxendd/fluxend/issues/87
**Changes**
- Adds `users/me` endpoint
- Endpoint automatically returns logged in user's response

[Feat] Add endpoint to show info of logged in user

---

web/app/routes/logs/log-detail-sheet.tsx

Fixes text overflow issue in the log detail sheet where long JSON content in Request Body and Query Parameters sections would extend beyond the container.
- Added `whitespace-pre-wrap` and `break-all` CSS classes to the `<pre>` elements
- This ensures long text wraps within the container instead of causing horizontal overflow
- Applied to both Request Body and Query Parameters sections
- Long JSON content would overflow horizontally requiring scrolling
- Made it difficult to read the full content on smaller screens
- Text wraps properly within the container
- All content is visible without horizontal scrolling
- Maintains JSON formatting while improving readability

fix: Add text wrapping to Request Body in log detail sheet

---

web/app/globals.css
web/app/routes/logs/log-detail-sheet.tsx
web/app/routes/projects/components/project-card.tsx
web/app/routes/tables/columns.tsx
web/app/routes/tables/table-list.tsx

Comprehensive fix for text overflow issues across multiple components in the application, ensuring long text content is properly handled without breaking layouts.
- Changed User Agent from `break-all` to `overflow-wrap-anywhere` for better word breaking
- Added `overflow-hidden` to badges containing endpoint and user UUID
- Made truncated spans use `block` display for proper truncation
- Added `max-w-[200px]` to column headers with truncation
- Added `max-w-[300px]` and title attributes to cell values for better UX
- Removed `whitespace-nowrap` that was preventing proper wrapping
- Added flex properties (`flex-1 min-w-0`) to allow proper truncation
- Added `flex-shrink-0` to icons and size indicators
- Added `max-w-[200px]` constraint to UUID display
- Added title attribute for full UUID …

fix: Improve text overflow handling across multiple components

---

web/app/routes/logs/log-detail-sheet.tsx

Fixes the issue where Request Body and Query Parameters in the log detail sheet were displaying stringified JSON instead of properly formatted parsed JSON.
- Added `parseJsonBody` helper function that:
- Returns objects as-is if already parsed
- Attempts to parse strings as JSON
- Falls back to original string if parsing fails
- Applied parsing to both Request Body and Query Parameters
- Maintained backward compatibility with already-parsed data
```json
"{\"columns\":[{\"name\":\"id\",\"type\":\"integer\"},{\"name\":\"name\",\"type\":\"varchar\"}]}"
```
```json
{
"columns": [
{
"name": "id",
"type": "integer"
},
{
"name": "name",
"type": "varchar"
}
]
}
```

fix: Parse JSON strings in Request Body and Query Parameters

---

web/app/routes/logs/columns.tsx
web/app/routes/logs/infinite-logs-table.tsx
web/app/routes/logs/page.tsx
web/app/services/logs.ts

- Replaces traditional pagination with infinite scroll in the logs page
- Implements virtual scrolling for better performance with large datasets
- Uses intersection observer to trigger loading of more data
- Maintains existing filtering and auto-refresh functionality
1. Created new `InfiniteLogsTable` component with:
- Virtual scrolling using @tanstack/react-virtual
- Intersection Observer for automatic load-more trigger
- Loading states and indicators
- Proper table layout for virtual rows
2. Updated logs page to:
- Use `useInfiniteQuery` instead of regular query
- Remove pagination state management
- Flatten paginated data for display
- Improve loading state presentation
3. Added `offset` support to logs service for cursor-based pagination
4. Fixed potential issues:
- Prevented row …

Fix: Replace pagination with infinite scroll in logs page

---

web/app/components/shared/project-sidebar.tsx

Enables tooltips for sidebar navigation items (Dashboard, Tables, Logs) to improve user experience by showing item names on hover in the icon-only sidebar.
Closes #125

feat: add tooltips to project sidebar menu items

---

web/app/routes/logs/page.tsx
web/app/routes/logs/virtualized-logs-table.tsx
web/app/services/logs.ts

- Remove PostgREST Prefer header that was causing server errors
- Switch to standard page-based pagination as per API documentation
- Implement table virtualization to fix performance issues with large datasets
- Removed `Prefer: count=exact` header that was causing 500 errors
- Removed PostgREST-specific offset/limit handling
- Simplified to use standard `page`, `limit`, `sort`, `order` parameters
- Changed from offset-based to page-based pagination
- Start with page 1 instead of offset 0
- Continue loading if full page received (instead of relying on totalCount)
- Created new virtualized table component using `@tanstack/react-virtual`
- Only renders visible rows (20-30) instead of thousands
- Maintains scroll position with calculated padding
- Prevents DOM memory issues and page hanging …

fix: Fix logs pagination and performance issues

---

web/app/lib/utils.ts
web/app/routes/logs/columns.tsx
web/app/routes/logs/log-detail-sheet.tsx
web/app/routes/logs/log-filters.tsx
web/app/routes/logs/page.tsx
web/app/services/logs.ts

This PR addresses multiple issues reported in #149 related to the logs page filtering functionality and display.
- **Fixed time-based filtering**: Removed `dateStart`/`dateEnd` parameters to use only `startTime`/`endTime` as the API expects
- **Timezone handling**: All timestamps now display in the user's local timezone while maintaining UTC for API communication
- **URL parameter sync**: Filter states are now reflected in the URL, allowing users to share and bookmark filtered views
- **Click interactions**: Fixed the issue where clicking on endpoint/IP fields wasn't opening the detail drawer
- **Clear filters button**: Now shows when a custom time range is applied (not just for non-time filters)
1. **API Integration**: Simplified to use only Unix timestamps (`startTime`/`endTime`)
2. …

Fix multiple issues with logs page filtering and display

---

web/.github/workflows/test.yml
web/app/components/ui/button.test.tsx
web/app/hooks/use-toast.test.tsx
web/app/lib/utils.test.ts
web/package.json
web/test/README.md
web/test/setup.ts
web/test/test-utils.tsx
web/test/vitest.d.ts
web/vitest.config.ts
web/yarn.lock

- Setup Vitest as the testing framework for the project
- Add React Testing Library for component testing
- Configure TypeScript path aliases and jsdom environment
- Add example tests and comprehensive documentation
- **Vitest 1.6.0** with React Testing Library, jsdom, and coverage support
- **Test configuration** with TypeScript path aliases and React plugin
- **Test utilities** with custom render function including providers (Router, QueryClient, Theme)
- **Example tests**:
- Unit tests for utilities (`formatTimestamp`, `formatCurrency`, `cn`)
- Component tests (Button component)
- Hook tests (useToast hook)
- **GitHub Actions workflow** for automated testing on PRs and pushes
- **Testing documentation** with best practices and common patterns
- **Test scripts**:
- `yarn test` - Run …

Setup Vitest testing framework

---

web/app/routes/auth/signup.tsx
web/app/routes/dashboard/page.tsx
web/app/routes/functions/page.tsx
web/app/routes/logs/page.tsx
web/app/routes/projects/page.tsx
web/app/routes/settings/page.tsx
web/app/routes/storage/page.tsx
web/app/routes/tables/page.tsx

This PR adds descriptive page titles to all routes that were missing them, making it easier to identify tabs when multiple are open.
- Added meta functions with titles to: Dashboard, Projects, Logs, Tables, Storage, Functions, and Settings routes
- Updated signup page title from "Frontend for Fluxend" to "Sign Up - Fluxend" for consistency
- All pages now follow the format "[Page Name] - Fluxend"
Before: Browser tabs show no titles or generic titles
After: Each tab shows descriptive titles like "Dashboard - Fluxend", "Logs - Fluxend", etc.
Closes #134

Fix: Add page titles to all routes for better tab identification

---

docs/openapi.json
docs/swagger.json
docs/swagger.yaml
internal/api/handlers/column.go
internal/api/routes/table.go
internal/database/repositories/column.go
internal/domain/database/column_repository.go
internal/domain/database/column_service.go

**Problem**
Update column endpoint was limited to changing types of columns only. This meant frontend will have to send separate requests for updating and deleting columns.
**Changes**
- Update behavior of endpoint to update columns included in request and delete ones missing
- Change request method from `PUT` to `PATCH` which is better suited for this behavior 
- Update documentation

[Fix] Modify Update Column Endpoint Behavior

---

web/app/routes/projects/page.tsx

This PR fixes the issue where users were not being redirected when their authentication token expired on the projects page.
- Added response status check in the projects page loader
- Implemented redirect to `/logout` when API calls fail (indicating expired token)
- Minor formatting fix for Textarea import
1. Navigate to the projects page with a valid token
2. Wait for token to expire or manually invalidate it
3. Refresh the page or trigger a loader
4. User should be redirected to logout page
Fixes #174

Fix: Redirect to logout on token expiry in projects page

---

.github/workflows/deploy.yml
internal/adapters/postgrest/service.go
internal/api/dto/logging/mapper.go
internal/api/dto/logging/requests.go
internal/api/handlers/project.go
internal/api/middlewares/request_logger.go
internal/api/routes/project.go
internal/database/repositories/request_log.go
internal/domain/logging/repository.go
internal/domain/logging/service.go
internal/domain/logging/types.go

**Why**
PostgREST requests are black hole at the moment. A user will have no idea what's happening in backend, how many requests are taking place and so on.
**Changes**
- Adds endpoint to capture logs
- Adds Traefik middleware to pass postgrest requests to endpoint

FLX-28: Enable PostgREST logs

---

web/app/routes/storage/index.tsx
web/app/routes/storage/sidebar.tsx
web/app/services/storage.ts

- Fixed the Create Container button in the storage index page that wasn't opening the dialog
- Pass setCreateContainerOpen callback through outlet context from sidebar to child routes
- This allows users to create containers when viewing the empty state message
Partially addresses #191 - the Create Container button now works when no containers exist
1. Navigate to Storage page with no containers
2. Click the "Create Container" button in the empty state
3. Verify the Create Container dialog opens
4. Create a container and verify navigation to the new container

Fix: Connect Create Container button in storage empty state

---

web/app/routes/logs/log-filters.tsx
web/app/routes/logs/logs-table.tsx
web/app/routes/logs/page.tsx

- Fixed theme flash issue that occurred when hard refreshing the logs page
- Resolved React hydration mismatches that were causing the theme to briefly show light mode before switching to dark mode
- Updated `LogFilters` component to handle timezone conversions consistently between server and client
- Added helper functions for UTC timestamp conversion to ensure consistent date handling
- Removed client-side timezone detection that was causing hydration mismatches
- All date/time operations now use UTC internally and convert to local timezone only for display
✅ Tested theme persistence on hard refresh - no flash observed
✅ Verified logs page loads directly in dark mode without any light theme flash
✅ Confirmed date filters still work correctly with proper timezone display
✅ Checked that …

Fix theme flash issue on logs page

---

docs/openapi.json
docs/swagger.json
docs/swagger.yaml
internal/adapters/storage/backblze_provider.go
internal/adapters/storage/dropbox_provider.go
internal/adapters/storage/provider.go
internal/adapters/storage/s3_provider.go
internal/api/dto/storage/file/responses.go
internal/api/handlers/file.go
internal/api/mapper/file.go
internal/api/routes/storage.go
internal/domain/storage/file/service.go

Users may want to download their uploaded files for different purposes. They may use UI only. Or they may need an endpoint for downloading in more seamless way.
Implements a new `/containers/{containerUUID}/files/{fileUUID}/download` endpoint that generates time-limited presigned URLs for secure file downloads.
Example response:
```json
{
"success": true,
"content": {
"url": "https://container-8dc0cb5672514fc591b90e6ecfdfd30a.s3.us-east-1.amazonaws.com/some-file-name.jpeg?X-Amz-Algorithm=....",
"expiresIn": 3600
}
}
```
- **New endpoint**: `GET /containers/{containerUUID}/files/{fileUUID}/download`
- **S3 Integration**: Added `CreatePresignedURL()` method to S3ServiceImpl
- **Security**: Generates secure, time-limited download URLs (no file content proxying)
- **Performance**: Direct …

[Feature] Support Storage File Download
